name: FastFood Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - run: dotnet restore
    - run: dotnet build --no-restore --configuration Release
    - run: dotnet publish -c Release -o ./publish

    - name: Zip publish folder
      run: zip -r FastFood.zip ./publish

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v1.0.${{ github.run_number }}
        name: "FastFood Build ${{ github.run_number }}"
        draft: false
        prerelease: false
        files: FastFood.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}